name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,test,vendor,diagram.svg,electron-builder.json,electron-builder-appx.json,licenses,package.json,package-lock.json,readme.md,rollup.config.js"
